---
title: "HL_210711_DepMap_tissue_specific_analysis"
author: Heyuan Li
date: "`r format(Sys.time(), '%B %d, $Y')`"
output: 
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(cache = TRUE)
knitr::opts_chunk$set(tidy.opts = list(width.cutoff = 60), tidy = TRUE)
knitr::opts_chunk$set(root.dir = "/storage/westbrook/projects/myc_hush/hush_depmap")

library(tidyverse)
library(pheatmap)
library(ggridges)

options(stringsAsFactors = FALSE)

mypal = c("#094074","#f2e2ba","#af3e4d","#5b618a","#9eadc8","#598392","#171614","#f3a712", "#5c8001","#19381f")

theme_set(
  theme_bw()
)
```

```{r load_data}
crispr_ceres = read.csv("/storage/westbrook/projects/correlation_tools/DepMap/data/200923_crispr_ceres.csv", row.names = 1)
#drive_demeter2 = read.csv("/storage/westbrook/projects/correlation_tools/DepMap/data/210405_drive_demeter2.csv", row.names = 1)
ccle_anno = read.csv("/storage/westbrook/projects/correlation_tools/DepMap/data/200923_ccle_anno.csv", row.names = 1)
corum = read_tsv("/storage/westbrook/projects/myc_hush/public_data/corum/coreComplexes.txt")
corum = subset(corum, Organism == "Human")

oncogenes = c('MYC','MYCN', 'MTOR', 'SRC', 'ALK', 'BCL2','CDK4','CDK6','CCND1','JUN','PIK3CA','AKT1','ABL1','BRAF','PDGFRA'
             , 'PDGFRB','FGFR1','EGFR','RAF1','MET','RAC1','MAPK1','KRAS','HRAS','AR','ERBB2','JAK2')
hush = c("MPHOSPH8","FAM208A","PPHLN1","ATF7IP","SETDB1","MORC2")

```

```{r formating}
genelist = lapply(corum$`subunits(Gene name)`,function(x){strsplit(x,split = ";")[[1]]})
names(genelist) = corum$ComplexID
genelist$hush = hush

NA2mean <- function(x) replace(x, is.na(x), median(x, na.rm = TRUE))
crispr_ceres[] <- lapply(crispr_ceres, NA2mean)

```

```{r line_score}
line_anno = ccle_anno[rownames(crispr_ceres), c(1,2,15,23)]
# sapply(crispr_ceres[,oncogene], function(x){
#   flag = rep(NA,length(x))
#   flag[x < quantile(x, 0.3)] = "dependent"
#   flag[x > quantile(x, 0.3)] = "independent"
# })

line_score = crispr_ceres[,hush]

tmp = lapply(genelist, function(genes){
  genes_exist = intersect(genes, colnames(crispr_ceres))
  if (length(genes_exist) > 2) {rowMeans(crispr_ceres[,genes_exist])}
   })
ave_dependency = Reduce(cbind, tmp[!sapply(tmp, is.null)])
colnames(ave_dependency) = names(tmp)[!sapply(tmp, is.null)]

line_score = cbind(line_score,ave_dependency)
```

```{r tissue_type}
tissue_type = table(line_anno$primary_disease)
tissue_type = tissue_type[tissue_type > 10]
tissue_type_list = lapply(names(tissue_type), function(tissue){
  rownames(subset(line_anno, primary_disease == tissue))
})
names(tissue_type_list) = names(tissue_type)
tissue_type_list$All = rownames(crispr_ceres)

```

```{r distance_matrix_for_complex}
# distance matrix
## assuming that taking means of the euclidean distances is fair to account for different numbers of members 
distance_matrix_for_complex = Reduce(cbind, lapply(tissue_type_list, function(lines){
  tmp = lapply(genelist, function(genes){
    genes_exist = intersect(genes, colnames(crispr_ceres))
    if (length(genes_exist) > 2) {
      m = scale(crispr_ceres[lines,genes_exist])
      mean(dist(t(m)))
      }
     })
  ave_dist = unlist(tmp[!sapply(tmp, is.null)])
  names(ave_dist) = names(tmp)[!sapply(tmp, is.null)]
  ave_dist
}))

colnames(distance_matrix_for_complex) = names(tissue_type_list)

# cor matrix
cor_matrix_for_complex = Reduce(cbind, lapply(tissue_type_list, function(lines){
  tmp = lapply(genelist, function(genes){
    genes_exist = intersect(genes, colnames(crispr_ceres))
    if (length(genes_exist) > 2) {
      mean(cor(crispr_ceres[lines,genes_exist]) * (1-diag(length(genes_exist))))
      }
     })
  ave_dist = unlist(tmp[!sapply(tmp, is.null)])
  names(ave_dist) = names(tmp)[!sapply(tmp, is.null)]
  ave_dist
}))

colnames(cor_matrix_for_complex) = names(tissue_type_list)


```

```{r hush_cor_tissue}
hush_cor_tissue = Reduce(rbind,lapply(tissue_type_list, function(lines){
  mean(cor(crispr_ceres[lines,hush]) * (1-diag(length(hush))))
}))
rownames(hush_cor_tissue) = names(tissue_type_list)

```

```{r oncogenes}
# correlations between hush and oncogenes
hush_cor = lapply(tissue_type_list, function(lines){
  subdata = crispr_ceres[lines,]
  res = sapply(oncogenes, function(oncogene){
    t(sapply(subdata[,hush], function(vec){cor(vec,subdata[,oncogene])}))
  })
  rownames(res) = hush
  res
})

# correlations between protein complex and MYC
genelist_nomyc = genelist[-which(sapply(genelist, function(gene) {sum(match("MYC", gene))}) > 0)]
ave_myc_cor = Reduce(cbind, lapply(tissue_type_list, function(lines){
  subdata = crispr_ceres[lines,]
  tmp = lapply(genelist_nomyc, function(genes){
    genes_exist = intersect(genes, colnames(subdata))
    if (length(genes_exist) > 2) {
      mean(sapply(subdata[,genes_exist], function(vec){cor(vec,subdata[,"MYC"])}))
      }
     })
  ave_cor = unlist(tmp[!sapply(tmp, is.null)])
  names(ave_cor) = names(tmp)[!sapply(tmp, is.null)]
  ave_cor
}))
colnames(ave_myc_cor) = names(tissue_type_list)

```

Visualizations 
1. Oncogenes vs. HuSH correlations
```{r oncogene_hush_heatmap}
## ALL cancer
pdata = hush_cor$All
pheatmap(as.matrix((pdata)))
  
## Breast
pdata = hush_cor$`Breast Cancer`
pheatmap(as.matrix((pdata)))
```

```{r oncogene_hush_ave}
## ALL cancer
pdata = data.frame("Oncogene" = colnames(hush_cor$All),
                   "Average_correlation_coefficients" = colMeans(hush_cor$All))
pdata = arrange(pdata, -Average_correlation_coefficients)
pdata$Oncogene = factor(pdata$Oncogene, levels = pdata$Oncogene)
ggplot(pdata, aes(Oncogene, Average_correlation_coefficients)) + 
  geom_bar(stat = "identity") +
  theme(axis.text.x = element_text(angle = 90))
  
## Breast
pdata = data.frame("Oncogene" = colnames(hush_cor$`Breast Cancer`),
                   "Average_correlation_coefficients" = colMeans(hush_cor$`Breast Cancer`))
pdata = arrange(pdata, -Average_correlation_coefficients)
pdata$Oncogene = factor(pdata$Oncogene, levels = pdata$Oncogene)
ggplot(pdata, aes(Oncogene, Average_correlation_coefficients)) + 
  geom_bar(stat = "identity") +
  theme(axis.text.x = element_text(angle = 90))

```
```{r ave_hush_tissue}
pdata = transform(line_score[,1:6], tissue_type = line_anno$primary_disease)
pdata = as.data.frame(group_by(pdata, tissue_type) %>% summarise_each(mean))
pdata = transform(pdata, row.names = pdata$tissue_type)
pdata$tissue_type = NULL

pheatmap(t(as.matrix(pdata)), breaks = seq(-1, 1, length.out = 100))
pheatmap(t(scale(as.matrix(pdata))))

pdata1 = data.frame("tissue" = rownames(pdata),
                   "Average_dependeny_scores" = rowMeans(pdata))
pdata1 = arrange(pdata1, Average_dependeny_scores)
pdata1$tissue = factor(pdata1$tissue, levels = pdata1$tissue)
ggplot(pdata1, aes(tissue, Average_dependeny_scores)) + 
  geom_bar(stat = "identity") +
  theme(axis.text.x = element_text(angle = 90))

```

```{r MYC_complex}
## ALL cancer
pdata = data.frame("id" = rownames(ave_myc_cor),
                   "complex" = corum$ComplexName[match(rownames(ave_myc_cor),corum$ComplexID)],
                   "Average_correlation_coefficients" = ave_myc_cor[,"All"])
pdata['hush','complex'] = 'HuSH (full) complex'
pdata = arrange(pdata, -Average_correlation_coefficients)
head(pdata,20)

pdata$id = factor(pdata$id, levels = unique(pdata$id))

ggplot(pdata, aes(id, Average_correlation_coefficients)) + 
  geom_bar(stat = "identity", color = "grey") +
  geom_bar(data = pdata['hush',], stat = "identity", color = "red") +
  ylim(-0.2,0.2) +
  ylab("Mean MYC correlation") +
  xlab("Protein complexes (CORUM)") +
  theme_bw() +
  theme(axis.text.x = element_blank(),
        axis.ticks = element_blank(),
        axis.line = element_line(color='black'),
        plot.background = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank())
  
## Breast
pdata = data.frame("id" = rownames(ave_myc_cor),
                   "complex" = corum$ComplexName[match(rownames(ave_myc_cor),corum$ComplexID)],
                   "Average_correlation_coefficients" = ave_myc_cor[,"Breast Cancer"])
pdata['hush','complex'] = 'HuSH (full) complex'
pdata = arrange(pdata, -Average_correlation_coefficients)
head(pdata,20)

pdata$id = factor(pdata$id, levels = unique(pdata$id))
ggplot(pdata, aes(id, Average_correlation_coefficients)) + 
  geom_point(stat = "identity") +
  geom_point(data = pdata['hush',], stat = "identity", color = "red") +
  theme(axis.text.x = element_blank())

```
```{r hush_intracor_tissue}
pdata = data.frame("tissue" = names(tissue_type_list),
                   "Average_pairwise_correlations" = rowMeans(hush_cor_tissue))
pdata = arrange(pdata, -Average_pairwise_correlations)
pdata$tissue = factor(pdata$tissue, levels = pdata$tissue)
ggplot(pdata, aes(tissue, Average_pairwise_correlations)) + 
  geom_bar(stat = "identity") +
  theme(axis.text.x = element_text(angle = 90))
  
```

```{r complex_intracor}
## all tumor
pdata = data.frame("id" = rownames(cor_matrix_for_complex),
                   "complex" = corum$ComplexName[match(rownames(cor_matrix_for_complex),corum$ComplexID)],
                   "Average_pairwise_cor" = cor_matrix_for_complex[,"All"])
pdata['hush','complex'] = 'HuSH (full) complex'
pdata = arrange(pdata, -Average_pairwise_cor)
head(pdata,20)

pdata$id = factor(pdata$id, levels = unique(pdata$id))
ggplot(pdata, aes(id, Average_pairwise_cor)) + 
  geom_point(stat = "identity") +
  geom_point(data = pdata['hush',], stat = "identity", color = "red") +
  theme(axis.text.x = element_blank())
  
## Breast
pdata = data.frame("id" = rownames(cor_matrix_for_complex),
                   "complex" = corum$ComplexName[match(rownames(cor_matrix_for_complex),corum$ComplexID)],
                   "Average_pairwise_cor" = cor_matrix_for_complex[,"Breast Cancer"])
pdata['hush','complex'] = 'HuSH (full) complex'
pdata = arrange(pdata, -Average_pairwise_cor)
head(pdata,20)

pdata$id = factor(pdata$id, levels = unique(pdata$id))
ggplot(pdata, aes(id, Average_pairwise_cor)) + 
  geom_point(stat = "identity") +
  geom_point(data = pdata['hush',], stat = "identity", color = "red") +
  theme(axis.text.x = element_blank())
```
```{r complex_intra_dist}
pdata = data.frame("id" = rownames(distance_matrix_for_complex),
                   "complex" = corum$ComplexName[match(rownames(distance_matrix_for_complex),corum$ComplexID)],
                   "Average_pairwise_distance" = distance_matrix_for_complex[,"All"])
pdata['hush','complex'] = 'HuSH (full) complex'
pdata = arrange(pdata, -Average_pairwise_distance)
tail(pdata,20)

pdata$id = factor(pdata$id, levels = unique(pdata$id))
ggplot(pdata, aes(id, Average_pairwise_distance)) + 
  geom_point(stat = "identity") +
  geom_point(data = pdata['hush',], stat = "identity", color = "red") +
  theme(axis.text.x = element_blank())
  
## Breast
pdata = data.frame("id" = rownames(distance_matrix_for_complex),
                   "complex" = corum$ComplexName[match(rownames(distance_matrix_for_complex),corum$ComplexID)],
                   "Average_pairwise_distance" = distance_matrix_for_complex[,"Breast Cancer"])
pdata['hush','complex'] = 'HuSH (full) complex'
pdata = arrange(pdata, -Average_pairwise_distance)
tail(pdata,20)

pdata$id = factor(pdata$id, levels = unique(pdata$id))
ggplot(pdata, aes(id, Average_pairwise_distance)) + 
  geom_point(stat = "identity") +
  geom_point(data = pdata['hush',], stat = "identity", color = "red") +
  theme(axis.text.x = element_blank())
```

```{r tissue_specific_cor, fig.align='center', fig.height=10, fig.width=15}
tissue_rho = Reduce(rbind,lapply(tissue_type_list, function(tissue){
  sapply(hush, function(gene){
    cor(crispr_ceres[tissue,gene], crispr_ceres[tissue,"MYC"])
  })
}))

rownames(tissue_rho) = names(tissue_type_list)

```

```{r plot, fig.align='center', fig.height=10, fig.width=13}
pdata = crispr_ceres[,c(hush,"MYC")]
pdata$Tissue_type = line_anno$primary_disease[match(rownames(pdata), rownames(line_anno))]
pdata = pdata[pdata$Tissue_type %in% names(tissue_type),]

ggplot(pdata, aes(MPHOSPH8,MYC)) + 
  geom_point() + 
  geom_smooth(method = "lm") +
  facet_wrap(~ Tissue_type, scales = "free") +
  xlim(-0.6, 0.4) +
  ylim(-3,0)
```
```{r plot2, fig.align='center', fig.height=6, fig.width=6}
pdata = crispr_ceres[,c("MYC",hush)]
pdata = reshape(pdata, direction = "long", varying = list(colnames(pdata)), timevar = "gene", v.names = "score", times = colnames(pdata), ids = rownames(pdata))
pdata$gene = factor(pdata$gene, levels = unique(pdata$gene), ordered = T)

ggplot(pdata, aes(score, gene)) + 
  geom_density_ridges(aes(fill = gene)) +
  scale_fill_manual(values = mypal[c(8, 1:6)]) + 
  ylab("") +
  theme(axis.ticks.y=element_blank(),  #remove y axis ticks
        panel.border = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank()
        )


```

```{r sessionInfo}
sessionInfo()
```